from django.utils.translation import gettext as _

WEEKDAYS = [
    ("MO", "Monday"),
    ("TU", "Tuesday"),
    ("WE", "Wednesday"),
    ("TH", "Thursday"),
    ("FR", "Friday"),
    ("SA", "Saturday"),
    ("SU", "Sunday"),
]


MONTHDAYS = [
    ("1MO", _("first monday")),
    ("1TU", _("first tuesday")),
    ("1WE", _("first wednesday")),
    ("1TH", _("first thursday")),
    ("1FR", _("first friday")),
    ("1SA", _("first saturday")),
    ("1SU", _("first sunday")),
    ("2MO", _("second monday")),
    ("2TU", _("second tuesday")),
    ("2WE", _("second wednesday")),
    ("2TH", _("second thursday")),
    ("2FR", _("second friday")),
    ("2SA", _("second saturday")),
    ("2SU", _("second sunday")),
    ("3MO", _("third monday")),
    ("3TU", _("third tuesday")),
    ("3WE", _("third wednesday")),
    ("3TH", _("third thursday")),
    ("3FR", _("third friday")),
    ("3SA", _("third saturday")),
    ("3SU", _("third sunday")),
    ("4MO", _("fourth monday")),
    ("4TU", _("fourth tuesday")),
    ("4WE", _("fourth wednesday")),
    ("4TH", _("fourth thursday")),
    ("4FR", _("fourth friday")),
    ("4SA", _("fourth saturday")),
    ("4SU", _("fourth sunday")),
    ("-1MO", _("last monday")),
    ("-1TU", _("last tuesday")),
    ("-1WE", _("last wednesday")),
    ("-1TH", _("last thursday")),
    ("-1FR", _("last friday")),
    ("-1SA", _("last saturday")),
    ("-1SU", _("last sunday")),
]

MONTHDATES = [(i, _("%s. day") % i) for i in range(1, 32)]

RRULE_MONTHLY_INTERVAL = [
    (1, _("every month")),
    (2, _("every 2nd month")),
    (3, _("every 3rd month")),
    (4, _("every 4th month")),
    (5, _("every 5th month")),
    (6, _("every 6th month")),
    (7, _("every 7th month")),
    (8, _("every 8th month")),
    (9, _("every 9th month")),
    (10, _("every 10th month")),
    (11, _("every 11th month")),
]

RRULE_WEEKLY_INTERVAL = [
    (1, _("every week")),
    (2, _("every 2nd week")),
    (3, _("every 3rd week")),
    (4, _("every 4th week")),
    (5, _("every 5th week")),
    (6, _("every 6th week")),
    (7, _("every 7th week")),
    (8, _("every 8th week")),
    (9, _("every 9th week")),
    (10, _("every 10th week")),
    (11, _("every 11th week")),
    (12, _("every 12th week")),
    (13, _("every 13th week")),
    (14, _("every 14th week")),
    (15, _("every 15th week")),
    (16, _("every 16th week")),
    (17, _("every 17th week")),
    (18, _("every 18th week")),
    (19, _("every 19th week")),
    (20, _("every 20th week")),
    (21, _("every 21st week")),
    (22, _("every 22nd week")),
    (23, _("every 23rd week")),
    (24, _("every 24th week")),
    (25, _("every 25th week")),
    (26, _("every 26th week")),
    (27, _("every 27th week")),
    (28, _("every 28th week")),
]

RRULE_DAILY_INTERVAL = [
    (1, _("every day")),
    (2, _("every 2nd day")),
    (3, _("every 3rd day")),
    (4, _("every 4th day")),
    (5, _("every 5th day")),
    (6, _("every 6th day")),
    (7, _("every 7th day")),
    (8, _("every 8th day")),
    (9, _("every 9th day")),
    (10, _("every 10th day")),
    (11, _("every 11th day")),
    (12, _("every 12th day")),
    (13, _("every 13th day")),
    (14, _("every 14th day")),
    (15, _("every 15th day")),
    (16, _("every 16th day")),
    (17, _("every 17th day")),
    (18, _("every 18th day")),
    (19, _("every 19th day")),
    (20, _("every 20th day")),
    (21, _("every 21st day")),
    (22, _("every 22nd day")),
    (23, _("every 23rd day")),
    (24, _("every 24th day")),
    (25, _("every 25th day")),
    (26, _("every 26th day")),
    (27, _("every 27th day")),
    (28, _("every 28th day")),
    (29, _("every 29th day")),
    (30, _("every 30th day")),
    (31, _("every 31st day")),
]
