# Generated by Django 5.1.5 on 2025-07-24 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0012_organization_public_name'),
        ('resources', '0013_location_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('organization_groups', models.ManyToManyField(blank=True, help_text='If no organization group is specified, the user can manage all bookings and organizations.', related_name='managers_of_organizationgroup', related_query_name='manager_of_organizationgroup', to='organizations.organizationgroup', verbose_name='Organization groups')),
                ('resources', models.ManyToManyField(related_name='managers_of_resource', related_query_name='manager_of_resource', to='resources.resource', verbose_name='Resources')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Manager',
                'ordering': ['id'],
            },
        ),
    ]
