# Generated by Django 4.2.11 on 2024-04-17 10:11

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('street', models.CharField(max_length=56, verbose_name='Street')),
                ('house_number', models.CharField(max_length=8, verbose_name='House Number')),
                ('zip_code', models.CharField(max_length=12, verbose_name='Zip Code')),
                ('city', models.CharField(max_length=24, verbose_name='City')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
