# Generated by Django 4.2.11 on 2024-06-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='certificate_of_tax_exemption',
            field=models.BooleanField(default=False, verbose_name='Certificate of tax exemption'),
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.IntegerField(choices=[(1, 'Without legal form'), (2, 'Registered association'), (3, 'Not registered association'), (4, 'Foundation'), (5, 'Civil law company'), (6, 'Limited company'), (7, 'Limited charitable company'), (8, 'Cooperative'), (9, 'Charitable cooperative'), (10, 'Individual entrepreneur'), (11, 'Other')], default=1, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='house_number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='House number'),
        ),
    ]
