# Generated by Django 4.2.11 on 2024-06-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_certificate_of_tax_exemption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='House number'),
            preserve_default=False,
        ),
    ]
