# Generated by Django 4.2.11 on 2024-06-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_remove_organization_type_organization_legal_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='legal_form',
            field=models.IntegerField(choices=[(1, 'Without legal form'), (2, 'Registered association'), (3, 'Not registered association'), (4, 'Foundation'), (5, 'Civil law company'), (6, 'Limited company'), (7, 'Limited charitable company'), (8, 'Cooperative'), (9, 'Charitable cooperative'), (10, 'Individual entrepreneur'), (11, 'Other')], verbose_name='Legal form'),
        ),
    ]
