# Generated by Django 4.2.11 on 2024-06-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_organization_legal_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationmembership',
            options={'ordering': ['id'], 'verbose_name': 'Organization membership', 'verbose_name_plural': 'Organization memberships'},
        ),
    ]
