# Generated by Django 5.1.1 on 2024-10-23 11:56

import roomsharing.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_defaultbookingstatus_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='usage_agreement',
            field=models.FileField(blank=True, null=True, upload_to='protected/usage_agreements/', validators=[roomsharing.organizations.models.validate_is_pdf], verbose_name='Usage agreement'),
        ),
    ]
