# Generated by Django 4.2.11 on 2024-06-16 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_organizations_tmp_user_organizations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0008_alter_organizationmembership_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationMembership',
            new_name='Membership',
        ),
    ]
