# Generated by Django 4.2.11 on 2024-06-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomimage'),
        ('organizations', '0010_alter_membership_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultBookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled')], verbose_name='Status')),
                ('organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='defaultbookingstatuses_of_organization', related_query_name='defaultbookingstatus_of_organization', to='organizations.organization', verbose_name='Organization')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaultbookingstatuses_of_room', related_query_name='defaultbookingstatus_of_room', to='rooms.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Default booking status',
                'verbose_name_plural': 'Default booking stati',
                'ordering': ['id'],
                'unique_together': {('room', 'organization')},
            },
        ),
    ]
