# Generated by Django 5.1.1 on 2024-11-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultbookingstatus',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Unavailable')], verbose_name='Status'),
        ),
    ]
