# Generated by Django 4.2.11 on 2024-06-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_defaultbookingstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultbookingstatus',
            options={'ordering': ['id'], 'verbose_name': 'Default booking status', 'verbose_name_plural': 'Default booking statuses'},
        ),
    ]
