# Generated by Django 4.2.11 on 2024-06-28 08:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_organizations_tmp_user_organizations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0012_alter_defaultbookingstatus_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='BookingPermission',
        ),
    ]
