# Generated by Django 4.2.11 on 2024-06-28 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0013_rename_membership_bookingpermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingpermission',
            options={'ordering': ['id'], 'verbose_name': 'Booking permission', 'verbose_name_plural': 'Booking permissions'},
        ),
        migrations.AlterField(
            model_name='bookingpermission',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations_of_bookingpermission', related_query_name='organization_of_bookingpermission', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='bookingpermission',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_of_bookingpermission', related_query_name='user_of_bookingpermission', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
