# Generated by Django 5.1.1 on 2024-12-16 13:55

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_alter_organization_usage_agreement'),
        ('rooms', '0009_alter_roomimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('description', models.CharField(max_length=2048, verbose_name='Description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('auto_confirmed_rooms', models.ManyToManyField(blank=True, related_name='autoconfirmedrooms_of_organizationgroup', related_query_name='autoconfirmedroom_of_organizationgroup', to='rooms.room', verbose_name='Auto confirmed rooms')),
            ],
            options={
                'verbose_name': 'User group',
                'verbose_name_plural': 'User groups',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_group',
            field=models.ManyToManyField(blank=True, related_name='organizations_of_organizationgroup', related_query_name='organization_of_organizationgroup', to='organizations.organizationgroup', verbose_name='Organization group'),
        ),
    ]
