# Generated by Django 5.1.1 on 2024-12-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_organizationgroup_organization_organization_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationgroup',
            options={'ordering': ['id'], 'verbose_name': 'Organization group', 'verbose_name_plural': 'Organization groups'},
        ),
        migrations.AddField(
            model_name='organizationgroup',
            name='show_on_organization_creation',
            field=models.BooleanField(default=False, verbose_name='Show on organization creation'),
        ),
        migrations.AddField(
            model_name='organizationgroup',
            name='show_on_organization_creation_wording',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='This will be displayed in the form'),
        ),
    ]
