# Generated by Django 5.1.1 on 2024-12-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_delete_defaultbookingstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='organization_group',
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_groups',
            field=models.ManyToManyField(blank=True, related_name='organizations_of_organizationgroups', related_query_name='organization_of_organizationgroups', to='organizations.organizationgroup', verbose_name='Organization group'),
        ),
    ]
