# Generated by Django 5.1.1 on 2024-12-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_remove_organization_organization_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationgroup',
            name='show_on_organization_creation_wording',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='This will be displayed in the form'),
            preserve_default=False,
        ),
    ]
