# Generated by Django 5.1.5 on 2025-02-06 16:18

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': [django.db.models.functions.text.Lower('first_name'), django.db.models.functions.text.Lower('last_name')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
