# Generated by Django 5.1.5 on 2025-07-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
