# Generated by Django 5.1.1 on 2024-12-16 13:55

import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_name_user_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('description', models.CharField(max_length=2048, verbose_name='Description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('users', models.ManyToManyField(related_name='usergroups_of_user', related_query_name='usergroup_of_user', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'User group',
                'verbose_name_plural': 'User groups',
                'ordering': ['id'],
            },
        ),
    ]
