# Generated by Django 5.1.1 on 2024-12-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_roomimage_image'),
        ('users', '0003_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='auto_confirm_organizations',
            field=models.BooleanField(default=False, verbose_name='Auto confirm organizations on creation'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='auto_confirmed_rooms',
            field=models.ManyToManyField(blank=True, related_name='autoconfirmedrooms_of_usergroup', related_query_name='autoconfirmedroom_of_usergroup', to='rooms.room', verbose_name='Auto confirmed rooms'),
        ),
    ]
