# Generated by Django 4.2.11 on 2024-07-29 08:20

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='Slug')),
                ('instructions', models.TextField(max_length=512, verbose_name='Instructions')),
            ],
            options={
                'verbose_name': 'Access',
                'verbose_name_plural': 'Accesses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=256, verbose_name='Code')),
                ('validity_start', models.DateTimeField(verbose_name='Validity start')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesscodes_of_access', related_query_name='accesscode_of_access', to='resources.access', verbose_name='Access')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations_of_access', related_query_name='organization_of_access', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Access code',
                'verbose_name_plural': 'Access codes',
                'ordering': ['validity_start'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms_of_access', related_query_name='room_of_access', to='resources.access', verbose_name='Access'),
        ),
    ]
