# Generated by Django 5.1.1 on 2025-01-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
