# Generated by Django 5.1.1 on 2024-12-29 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='resource',
            field=models.ManyToManyField(related_name='compensations_of_resource', related_query_name='compensation_of_resource', to='resources.resource', verbose_name='Resource'),
        ),
        migrations.AddField(
            model_name='resourceimage',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourceimages_of_resource', related_query_name='resourceimage_of_resource', to='resources.resource', verbose_name='Resource'),
        ),
    ]
