# Generated by Django 5.1.1 on 2025-01-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_compensation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Only bookable with specific permissions', verbose_name='Private'),
        ),
    ]
