# Generated by Django 5.1.1 on 2024-09-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_access_accesscode_room_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('conditions', models.CharField(blank=True, max_length=512, verbose_name='Conditions')),
                ('hourly_rate', models.IntegerField(blank=True, null=True, verbose_name='Hourly Rate')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations_of_room', related_query_name='compensation_of_room', to='resources.room', verbose_name='Resource')),
            ],
            options={
                'verbose_name': 'Compensation',
                'verbose_name_plural': 'Compensations',
            },
        ),
    ]
