# Generated by Django 5.1.1 on 2025-01-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='pricing',
        ),
    ]
