# Generated by Django 5.1.1 on 2024-09-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_compensation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensation',
            name='room',
        ),
        migrations.AddField(
            model_name='compensation',
            name='room',
            field=models.ManyToManyField(related_name='compensations_of_room', related_query_name='compensation_of_room', to='resources.room', verbose_name='Resource'),
        ),
    ]
