# Generated by Django 5.1.1 on 2025-01-21 19:25

import django.core.validators
import re_sharing.resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceimage',
            name='image',
            field=models.ImageField(storage=re_sharing.resources.models.select_default_storage, upload_to='resource_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
