# Generated by Django 5.1.5 on 2025-02-06 16:18

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resourceimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compensation',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'Compensation', 'verbose_name_plural': 'Compensations'},
        ),
    ]
