# Generated by Django 5.1.1 on 2024-10-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_compensation_room_compensation_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bookable_equipment',
        ),
        migrations.AddField(
            model_name='room',
            name='accessibility',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Accessibility'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Description'),
        ),
    ]
