# Generated by Django 5.1.5 on 2025-02-07 15:19

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_compensation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='Slug'),
        ),
    ]
