# Generated by Django 5.1.1 on 2024-10-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_room_accessibility_alter_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.CharField(default='Rehlingstraße 9, 79100 Freiburg im Breisgau', max_length=256, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
