# Generated by Django 5.1.5 on 2025-02-07 15:21

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_compensation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensation',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('name', 'hourly_rate'), verbose_name='Slug'),
        ),
    ]
