# Generated by Django 5.1.5 on 2025-02-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_compensation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('room', 'Room'), ('parking_lot', 'Parking lot')], default='room', max_length=50),
            preserve_default=False,
        ),
    ]
