# Generated by Django 5.1.5 on 2025-02-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_organization_options'),
        ('resources', '0008_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='organization_groups',
            field=models.ManyToManyField(related_name='compensations_of_organizationgroup', related_query_name='compensation_of_organizationgroup', to='organizations.organizationgroup', verbose_name='Organization group'),
        ),
    ]
