# Generated by Django 5.1.5 on 2025-03-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_organization_options'),
        ('resources', '0009_compensation_organization_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensation',
            name='organization_groups',
            field=models.ManyToManyField(blank=True, help_text='If no group is selected, the compensation is bookable for all organizations.', related_name='compensations_of_organizationgroup', related_query_name='compensation_of_organizationgroup', to='organizations.organizationgroup', verbose_name='Organization group'),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='resource',
            field=models.ManyToManyField(blank=True, help_text='If no resource is selected, the compensation is bookable for all resources.', related_name='compensations_of_resource', related_query_name='compensation_of_resource', to='resources.resource', verbose_name='Resource'),
        ),
    ]
