# Generated by Django 5.1.5 on 2025-04-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_organization_options'),
        ('resources', '0010_alter_compensation_organization_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('start_time', models.TimeField(help_text='Start time of the restriction.', verbose_name='Start time')),
                ('end_time', models.TimeField(help_text='End time of the restriction.', verbose_name='End time')),
                ('days_of_week', models.CharField(help_text='Comma-separated list of weekday numbers (0=Monday, 6=Sunday).', max_length=13, verbose_name='Days of week')),
                ('message', models.CharField(help_text='Message to display when the restriction applies.', max_length=512, verbose_name='Message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('exempt_organization_groups', models.ManyToManyField(blank=True, help_text='Organizations in these groups are exempt from this restriction.', related_name='exempt_restrictions_of_organizationgroup', related_query_name='exempt_restriction_of_organizationgroup', to='organizations.organizationgroup', verbose_name='Exempt organization groups')),
                ('resources', models.ManyToManyField(help_text='Select the resources this restriction applies to.', related_name='restrictions_of_resource', related_query_name='restriction_of_resource', to='resources.resource', verbose_name='Resources')),
            ],
            options={
                'verbose_name': 'Resource restriction',
                'verbose_name_plural': 'Resource restrictions',
                'ordering': ['id'],
            },
        ),
    ]
