# Generated by Django 4.2.7 on 2023-11-30 12:00

from django.db import migrations
from django_extensions.db.fields import AutoSlugField


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_location_remove_resource_address_resource_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=AutoSlugField(populate_from='name', editable=False, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
