# Generated by Django 5.2.7 on 2025-11-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_location_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerestriction',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the restriction. Leave empty to apply indefinitely.', null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='resourcerestriction',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the restriction. Leave empty to apply from the beginning.', null=True, verbose_name='Start date'),
        ),
    ]
