# Generated by Django 6.0 on 2026-01-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_add_date_range_to_resource_restriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='square_meters',
        ),
        migrations.AddField(
            model_name='compensation',
            name='daily_rate',
            field=models.IntegerField(blank=True, help_text='Price per calendar day. Only applicable for lendable items.', null=True, verbose_name='Daily Rate'),
        ),
        migrations.AddField(
            model_name='resource',
            name='quantity_available',
            field=models.PositiveIntegerField(blank=True, help_text='Number of items in stock. Only applicable for lendable items.', null=True, verbose_name='Quantity available'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='max_persons',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Number of Persons'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('room', 'Room'), ('parking_lot', 'Parking lot'), ('lendable_item', 'Lendable item')], max_length=50),
        ),
    ]
