# Generated by Django 6.0.2 on 2026-02-19 08:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_organization_show_bookings_on_info_screens'),
        ('resources', '0015_remove_resource_square_meters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Name')),
                ('code', models.CharField(max_length=256, verbose_name='Code')),
                ('validity_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Validity start')),
                ('validity_end', models.DateTimeField(blank=True, null=True, verbose_name='Validity end')),
                ('accesses', models.ManyToManyField(related_name='permanentcodes_of_access', related_query_name='permanentcode_of_access', to='resources.access', verbose_name='Accesses')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations_of_permanentcode', related_query_name='organization_of_permanentcode', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Permanent code',
                'verbose_name_plural': 'Permanent codes',
                'ordering': ['validity_start'],
            },
        ),
    ]
