# Generated by Django 6.0.2 on 2026-02-19 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_permanentcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='parent_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_accesses', to='resources.access', verbose_name='Parent Access'),
        ),
        migrations.AddField(
            model_name='access',
            name='smartlock_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Smartlock ID'),
        ),
    ]
