# Generated by Django 6.0.2 on 2026-02-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_access_parent_access_access_smartlock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensation',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per calendar day. Only applicable for lendable items.', max_digits=6, null=True, verbose_name='Daily Rate'),
        ),
    ]
