# Generated by Django 6.0.3 on 2026-10-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_organizationgroup_free_bookings'),
        ('resources', '0019_remove_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='counts_against_free_bookings',
            field=models.BooleanField(default=False, help_text="Bookings with this compensation use one of the organization's free bookings per year. Only possible for compensations without a rate.", verbose_name='Counts against free bookings'),
        ),
        migrations.AddConstraint(
            model_name='compensation',
            constraint=models.CheckConstraint(condition=models.Q(('counts_against_free_bookings', False), models.Q(('hourly_rate__isnull', True), ('daily_rate__isnull', True)), _connector='OR'), name='compensation_free_bookings_flag_only_without_rate', violation_error_message='A compensation with a rate cannot count against free bookings.'),
        ),
    ]
