# Generated by Django 4.2.11 on 2024-07-06 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('street', models.CharField(max_length=56, verbose_name='Street')),
                ('house_number', models.CharField(blank=True, max_length=8, verbose_name='House number')),
                ('zip_code', models.CharField(max_length=12, verbose_name='Zip Code')),
                ('city', models.CharField(max_length=24, verbose_name='City')),
                ('legal_form', models.IntegerField(choices=[(1, 'Without legal form'), (2, 'Registered association'), (3, 'Not registered association'), (4, 'Foundation'), (5, 'Civil law company'), (6, 'Limited company'), (7, 'Limited charitable company'), (8, 'Cooperative'), (9, 'Charitable cooperative'), (10, 'Individual entrepreneur'), (11, 'Other')], verbose_name='Legal form')),
                ('certificate_of_tax_exemption', models.BooleanField(default=False, verbose_name='Certificate of tax exemption')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DefaultBookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled')], verbose_name='Status')),
                ('organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='defaultbookingstatuses_of_organization', related_query_name='defaultbookingstatus_of_organization', to='organizations.organization', verbose_name='Organization')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaultbookingstatuses_of_room', related_query_name='defaultbookingstatus_of_room', to='resources.room', verbose_name='Resource')),
            ],
            options={
                'verbose_name': 'Default booking status',
                'verbose_name_plural': 'Default booking statuses',
                'ordering': ['id'],
                'unique_together': {('room', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='BookingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('role', models.IntegerField(choices=[(1, 'Administrator'), (2, 'Booker')], default=2, verbose_name='Role')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Rejected')], default=1, verbose_name='Status')),
                ('organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations_of_bookingpermission', related_query_name='organization_of_bookingpermission', to='organizations.organization', verbose_name='Organization')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_of_bookingpermission', related_query_name='user_of_bookingpermission', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Booking permission',
                'verbose_name_plural': 'Booking permissions',
                'ordering': ['id'],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
