# Generated by Django 5.1.1 on 2024-12-29 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpermission',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_of_bookingpermission', related_query_name='user_of_bookingpermission', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='bookingpermission',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations_of_bookingpermission', related_query_name='organization_of_bookingpermission', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='organizationgroup',
            name='auto_confirmed_resources',
            field=models.ManyToManyField(blank=True, related_name='autoconfirmedresources_of_organizationgroup', related_query_name='autoconfirmedresource_of_organizationgroup', to='resources.resource', verbose_name='Auto confirmed resources'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_groups',
            field=models.ManyToManyField(blank=True, related_name='organizations_of_organizationgroups', related_query_name='organization_of_organizationgroups', to='organizations.organizationgroup', verbose_name='Organization group'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingpermission',
            unique_together={('user', 'organization')},
        ),
    ]
