# Generated by Django 4.2.11 on 2024-08-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='certificate_of_tax_exemption',
        ),
        migrations.AddField(
            model_name='organization',
            name='charitable',
            field=models.BooleanField(default=False, help_text='Only applicable if you have a valid certificate of tax exemption.', verbose_name='Charitable'),
        ),
        migrations.AddField(
            model_name='organization',
            name='other_legal_form',
            field=models.CharField(blank=True, max_length=160, verbose_name='Other legal form'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_form',
            field=models.IntegerField(choices=[(1, 'Without legal form'), (2, 'Registered association'), (3, 'Not registered association'), (4, 'Foundation'), (5, 'Civil law company'), (6, 'Limited company'), (8, 'Cooperative'), (10, 'Individual entrepreneur'), (11, 'Other')], verbose_name='Legal form'),
        ),
    ]
