# Generated by Django 4.2.11 on 2024-08-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_certificate_of_tax_exemption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Rejected')], default=1, verbose_name='Status'),
        ),
    ]
