# Generated by Django 4.2.11 on 2024-08-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='charitable',
            new_name='is_charitable',
        ),
    ]
