# Generated by Django 5.1.1 on 2025-01-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_emailtemplate_email_type'),
        ('resources', '0003_resource_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationgroup',
            name='bookable_private_resources',
            field=models.ManyToManyField(blank=True, related_name='bookableprivateressources_of_organizationgroup', related_query_name='bookableprivateressource_of_organizationgroup', to='resources.resource', verbose_name='Bookable private resources'),
        ),
    ]
