# Generated by Django 5.1.1 on 2025-01-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationgroup_bookable_private_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_coworking',
        ),
    ]
