# Generated by Django 5.1.1 on 2024-09-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_rename_charitable_organization_is_charitable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='street',
        ),
        migrations.AddField(
            model_name='organization',
            name='area_of_activity',
            field=models.IntegerField(choices=[(1, 'Sport and exercise'), (2, 'Culture and music'), (3, 'Social area'), (4, 'School or nursery area'), (5, 'Church or religious area'), (6, 'Leisure and social interaction'), (7, 'Environment, nature protection or animal rights'), (8, 'Youth work outside school or adult education'), (9, 'Politics and political interest groups'), (10, 'Accident or ambulance service or voluntary fire brigade'), (11, 'Health area'), (12, 'Professional interest groups outside work'), (13, 'Justice and criminality'), (14, 'Area not yet mentioned')], default=1, verbose_name='Main area of activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.CharField(default='Just great', help_text='Describe shortly what your organization does.', max_length=512, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(default='test@haus-des-engagements.de', max_length=64, verbose_name='E-Mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='entitled',
            field=models.BooleanField(default=True, verbose_name='Approval of entitlement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='is_coworking',
            field=models.BooleanField(default=False, help_text='Only applicable if you are currently co-working in the HdE', verbose_name='Co-Worker:in'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_public',
            field=models.BooleanField(default=True, help_text="If checked, we'll show the following information to others: name, description, city, website, area of activity", verbose_name='Organization information is publicly visible'),
        ),
        migrations.AddField(
            model_name='organization',
            name='notes',
            field=models.CharField(blank=True, help_text='Internal notes', max_length=512, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(default='0000', max_length=32, verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='street_and_housenb',
            field=models.CharField(default='Rehlingstr 9', max_length=56, verbose_name='Street and housenumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='values_approval',
            field=models.BooleanField(default=True, verbose_name='Approval of values'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=128, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_charitable',
            field=models.BooleanField(default=False, help_text='Only applicable if you have a valid certificate of tax exemption.', verbose_name='We are a charitable organization.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_form',
            field=models.IntegerField(choices=[(1, 'Without legal form'), (2, 'Registered association'), (3, 'Not registered association'), (4, 'Foundation'), (5, 'Civil law company'), (6, 'Limited company'), (7, 'Cooperative'), (8, 'Individual entrepreneur'), (9, 'Other')], verbose_name='Legal form'),
        ),
    ]
