# Generated by Django 5.1.1 on 2025-01-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_organization_is_coworking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['email_type'], 'verbose_name': 'E-Mail template', 'verbose_name_plural': 'E-Mail template'},
        ),
    ]
