# Generated by Django 5.1.1 on 2024-10-15 11:03

import re_sharing.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='usage_agreement',
            field=models.FileField(blank=True, null=True, upload_to='protected/usage_agreements/', validators=[re_sharing.organizations.models.validate_is_pdf]),
        ),
    ]
