# Generated by Django 5.1.5 on 2025-01-22 13:25

import re_sharing.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_emailtemplate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='usage_agreement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of the signed usage agreement'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='usage_agreement',
            field=models.FileField(blank=True, null=True, storage=re_sharing.organizations.models.select_private_storage, upload_to=re_sharing.organizations.models.custom_usage_agreement_upload_to, validators=[re_sharing.organizations.models.validate_is_pdf], verbose_name='Usage agreement'),
        ),
    ]
