# Generated by Django 5.1.1 on 2024-10-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_usage_agreement'),
        ('resources', '0006_alter_room_accessibility_alter_room_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='defaultbookingstatus',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(help_text='Describe shortly what your organization does.', max_length=2048, verbose_name='Description'),
        ),
        migrations.RemoveField(
            model_name='defaultbookingstatus',
            name='room',
        ),
        migrations.AddField(
            model_name='defaultbookingstatus',
            name='room',
            field=models.ManyToManyField(related_name='defaultbookingstatuses_of_room', related_query_name='defaultbookingstatus_of_room', to='resources.room', verbose_name='Rooms'),
        ),
    ]
