# Generated by Django 5.1.5 on 2025-01-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_usage_agreement_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='entitled',
        ),
    ]
