# Generated by Django 5.1.5 on 2025-02-02 20:52

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_remove_organization_entitled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
    ]
