# Generated by Django 5.1.5 on 2025-05-05 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_organization_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking confirmation'), ('booking_cancellation', 'Booking cancellation'), ('booking_reminder', 'Booking reminder'), ('booking_series_confirmation', 'Booking series confirmation'), ('booking_series_cancellation', 'Booking series cancellation'), ('organization_confirmation', 'Organization confirmation'), ('organization_cancellation', 'Organization cancellation'), ('manager_new_organization', 'Manager new organization'), ('manager_new_booking_series', 'Manager new booking series'), ('manager_new_booking', 'Manager new booking'), ('new_booking_message', 'New booking message'), ('new_organization_message', 'New organization message')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='OrganizationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('text', models.CharField(max_length=800, verbose_name='Message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationmessages_of_organization', related_query_name='organizationmessage_of_organization', to='organizations.organization', verbose_name='Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizationmessages_of_user', related_query_name='organizationmessage_of_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Organization Message',
                'verbose_name_plural': 'Organization Messages',
                'ordering': ['created'],
            },
        ),
    ]
