# Generated by Django 5.1.1 on 2024-10-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_organization_usage_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('email_type', models.CharField(choices=[('booking_confirmation', 'Booking confirmation'), ('booking_cancellation', 'Booking cancellation'), ('booking_reminder', 'Booking reminder'), ('recurrence_confirmation', 'Recurrence confirmation'), ('recurrence_cancellation', 'Recurrence cancellation'), ('organization_confirmation', 'Organization confirmation'), ('organization_cancellation', 'Organization cancellation'), ('manager_new_organization', 'Manager new organization'), ('manager_new_recurrence', 'Manager new recurrence'), ('manager_new_booking', 'Manager new booking')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
