# Generated by Django 5.1.5 on 2025-06-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_alter_emailtemplate_email_type_organizationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking confirmation'), ('booking_cancellation', 'Booking cancellation'), ('booking_reminder', 'Booking reminder'), ('booking_series_confirmation', 'Booking series confirmation'), ('booking_series_cancellation', 'Booking series cancellation'), ('organization_confirmation', 'Organization confirmation'), ('organization_cancellation', 'Organization cancellation'), ('manager_new_organization', 'Manager new organization'), ('manager_new_booking_series', 'Manager new booking series'), ('manager_new_booking', 'Manager new booking'), ('manager_new_organization_message', 'Manager new organization message'), ('new_booking_message', 'New booking message'), ('new_organization_message', 'New organization message')], max_length=50, unique=True),
        ),
    ]
