# Generated by Django 5.1.5 on 2025-07-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_emailtemplate_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='public_name',
            field=models.CharField(blank=True, help_text='This is the name that appears on the public timetables. Only relevant if you wish to hide your official name publicly.', max_length=160, verbose_name='Public name'),
        ),
    ]
