# Generated by Django 5.1.1 on 2024-12-10 10:52

import re_sharing.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_alter_organization_usage_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='usage_agreement',
            field=models.FileField(blank=True, null=True, upload_to='usage_agreements/', validators=[re_sharing.organizations.models.validate_is_pdf], verbose_name='Usage agreement'),
        ),
    ]
