# Generated by Django 5.1.5 on 2025-07-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_organization_public_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='monthly_bulk_access_codes',
            field=models.BooleanField(default=False, verbose_name='All access codes for the next month will be sent in one mail on the 20th.'),
        ),
    ]
