# Generated by Django 5.1.5 on 2025-08-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_organization_monthly_bulk_access_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='send_booking_emails_only_to_organization',
            field=models.BooleanField(default=False, verbose_name='All mails will be send to the organization and not to the user.'),
        ),
    ]
