# Generated by Django 5.1.5 on 2025-08-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_alter_organization_send_booking_emails_only_to_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationgroup',
            name='default_group',
            field=models.BooleanField(default=False, verbose_name='Group activated by default'),
        ),
    ]
