# Generated by Django 5.1.5 on 2025-08-15 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_organizationgroup_default_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookingpermission',
            index=models.Index(fields=['user', 'organization', 'status'], name='organizatio_user_id_26baa3_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpermission',
            index=models.Index(fields=['organization', 'role', 'status'], name='organizatio_organiz_30ee0d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingpermission',
            index=models.Index(fields=['user', 'status'], name='organizatio_user_id_f0df1f_idx'),
        ),
    ]
