# Generated by Django 5.1.1 on 2024-12-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_alter_organizationgroup_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultBookingStatus',
        ),
    ]
