# Generated by Django 5.1.5 on 2025-09-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_alter_emailtemplate_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=128, verbose_name='Website'),
        ),
    ]
