# Generated by Django 6.0 on 2026-02-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_alter_emailtemplate_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_groups',
            field=models.ManyToManyField(related_name='organizations_of_organizationgroups', related_query_name='organization_of_organizationgroups', to='organizations.organizationgroup', verbose_name='Organization group'),
        ),
    ]
