# Generated by Django 5.1.1 on 2024-12-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_alter_organizationgroup_show_on_organization_creation_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='send_booking_emails_only_to_organization',
            field=models.BooleanField(default=False, verbose_name='All mails for bookings will be send to the organization and not to the booking user.'),
        ),
    ]
