# Generated by Django 6.0.2 on 2026-02-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_alter_organization_organization_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='show_bookings_on_info_screens',
            field=models.BooleanField(default=True, help_text='If enabled, your bookings will show up on the info screens at the entrance of the meeting location.', verbose_name='Show bookings on public info screens at the entrance of the meeting location'),
        ),
    ]
