# Generated by Django 5.1.1 on 2024-12-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_organization_send_booking_emails_only_to_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Send this email out.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking confirmation'), ('booking_cancellation', 'Booking cancellation'), ('booking_reminder', 'Booking reminder'), ('recurrence_confirmation', 'Recurrence confirmation'), ('recurrence_cancellation', 'Recurrence cancellation'), ('organization_confirmation', 'Organization confirmation'), ('organization_cancellation', 'Organization cancellation'), ('manager_new_organization', 'Manager new organization'), ('manager_new_recurrence', 'Manager new recurrence'), ('manager_new_booking', 'Manager new booking'), ('new_booking_message', 'New booking message')], max_length=50, unique=True),
        ),
    ]
