# Generated by Django 6.0.2 on 2026-02-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_organization_show_bookings_on_info_screens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking confirmation'), ('booking_cancellation', 'Booking cancellation'), ('booking_reminder', 'Booking reminder'), ('booking_series_confirmation', 'Booking series confirmation'), ('booking_series_cancellation', 'Booking series cancellation'), ('organization_confirmation', 'Organization confirmation'), ('organization_cancellation', 'Organization cancellation'), ('manager_new_organization', 'Manager new organization'), ('manager_new_booking_series', 'Manager new booking series'), ('manager_new_booking', 'Manager new booking'), ('manager_new_organization_message', 'Manager new organization message'), ('new_booking_message', 'New booking message'), ('new_organization_message', 'New organization message'), ('monthly_bookings', 'Monthly bookings'), ('booking_not_available', 'Booking not available'), ('permanent_code_created', 'Permanent code created'), ('permanent_code_renewed', 'Permanent code renewed'), ('permanent_code_invalidated', 'Permanent code invalidated')], max_length=50, unique=True),
        ),
    ]
