# Generated by Django 6.0.2 on 2026-03-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_alter_emailtemplate_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmessage',
            name='text',
            field=models.CharField(max_length=2048, verbose_name='Message'),
        ),
    ]
