# Generated by Django 6.0.3 on 2026-06-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_alter_organizationmessage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Rejected'), (4, 'Deactivated')], default=1, verbose_name='Status'),
        ),
    ]
