# Generated by Django 6.0.3 on 2026-10-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_alter_organization_status'),
        ('resources', '0019_remove_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationgroup',
            name='free_bookings_per_year',
            field=models.PositiveIntegerField(blank=True, help_text='Number of free bookings per calendar year for organizations in this group. Leave empty for unlimited free bookings. An organization gets the most generous allowance of all its groups. Changes only affect bookings made afterwards.', null=True, verbose_name='Free bookings per year'),
        ),
        migrations.AddField(
            model_name='organizationgroup',
            name='free_bookings_valid_from',
            field=models.DateField(blank=True, help_text='Bookings starting on or after this date count against the free bookings. Required when a number of free bookings is set.', null=True, verbose_name='Free bookings limit valid from'),
        ),
        migrations.AddConstraint(
            model_name='organizationgroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('free_bookings_per_year__isnull', True), ('free_bookings_valid_from__isnull', True)), models.Q(('free_bookings_per_year__isnull', False), ('free_bookings_valid_from__isnull', False)), _connector='OR'), name='organizationgroup_free_bookings_fields_set_together', violation_error_message='Free bookings per year and the valid-from date have to be set together.'),
        ),
    ]
