# Generated by Django 4.2.11 on 2024-05-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_booking_group_booking_organization_and_more'),
        ('organizations', '0001_initial'),
        ('users', '0003_alter_user_organizations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='users_of_organization', related_query_name='user_of_organization', to='organizations.organization', verbose_name='Organizations'),
        ),
    ]
