# Generated by Django 4.2.11 on 2024-06-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_organization_alter_user_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Freiburg im Breisgau', max_length=24, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='house_number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='House Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=0, max_length=20, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(default='Rehlngstraße', max_length=56, verbose_name='Street'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='79100', max_length=12, verbose_name='Zip Code'),
            preserve_default=False,
        ),
    ]
