# Generated by Django 4.2.11 on 2024-06-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='House Number'),
            preserve_default=False,
        ),
    ]
