# Generated by Django 4.2.11 on 2024-06-07 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationmembership'),
        ('users', '0007_alter_user_house_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organizations',
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='organizations_tmp',
            field=models.ManyToManyField(blank=True, related_name='users_of_organization', related_query_name='user_of_organization', through='organizations.OrganizationMembership', to='organizations.organization', verbose_name='Organizations'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
