# Generated by Django 4.2.11 on 2024-06-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_organizations_user_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organizations_tmp',
            new_name='organizations',
        ),
    ]
