# Generated by Django 4.2.11 on 2024-07-06 15:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import roomsharing.rooms.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=160, verbose_name='Title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('description', models.TextField(max_length=512, verbose_name='Description')),
                ('square_meters', models.PositiveIntegerField(blank=True, null=True, verbose_name='Square Meters')),
                ('max_persons', models.PositiveIntegerField(default=5, verbose_name='Maximum Number of Persons')),
                ('bookable_times', models.CharField(blank=True, max_length=128, verbose_name='General Bookable Times')),
                ('pricing', models.TextField(blank=True, max_length=512, verbose_name='Pricing conditions')),
                ('included_equipment', models.TextField(blank=True, max_length=512, verbose_name='Included Equipment')),
                ('bookable_equipment', models.TextField(blank=True, max_length=512, verbose_name='Bookable Equipment')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('image', models.ImageField(upload_to=roomsharing.rooms.models.create_roomimage_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Description')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomimages_of_room', related_query_name='roomimage_of_room', to='rooms.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
            },
        ),
    ]
