# Generated by Django 4.2.11 on 2024-03-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="pricing",
            field=models.TextField(
                blank=True, max_length=512, verbose_name="Pricing conditions"
            ),
        ),
    ]
