# Generated by Django 4.2.11 on 2024-05-22 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import roomsharing.rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('image', models.ImageField(upload_to=roomsharing.rooms.models.create_roomimage_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Description')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomimages_of_room', related_query_name='roomimage_of_room', to='rooms.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
            },
        ),
    ]
