# Generated by Django 4.2.11 on 2024-03-29 15:02

from django.db import migrations
from roomsharing.rooms.models import Room

from django.db import migrations

ROOMS_DATA = [
    {"name": "Co-Working-Space", "description": "desc", "max_persons": 30},
    {"name": "Grüner Raum (großer Meetingraum)", "description": "desc", "max_persons": 10},
    {"name": "Gelber Raum (hinten links)", "description": "desc", "max_persons": 8},
    {"name": "Oranger Raum (ganz kleiner Meetingraum)", "description": "desc", "max_persons": 4},
    {"name": "Weißer Raum (EG)", "description": "desc", "max_persons": 15},
    {"name": "Türkiser Raum (EG)", "description": "desc", "max_persons": 8},
    {"name": "Veranstaltungsraum (EG)", "description": "desc", "max_persons": 60},
]

def populate_example_room_data(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    for room_data in ROOMS_DATA:
        Room.objects.create(**room_data)

def reverse_populate_example_room_data(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    for room_data in ROOMS_DATA:
        Room.objects.filter(name=room_data['name']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_room_pricing"),
    ]

    operations = [
        migrations.RunPython(populate_example_room_data, reverse_populate_example_room_data),
    ]
