# Generated by Django 5.1.1 on 2024-10-15 07:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_remove_room_bookable_equipment_room_accessibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='accessibility',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, verbose_name='Accessibility'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, verbose_name='Description'),
        ),
    ]
