# Generated by Django 5.1.1 on 2024-12-29 09:14

import django.contrib.postgres.fields.ranges
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=160, verbose_name='Title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['start_date', 'title'])),
                ('timespan', django.contrib.postgres.fields.ranges.DateTimeRangeField(default_bounds='()', verbose_name='Date Time Range')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Unavailable')], verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total amount')),
                ('invoice_number', models.CharField(blank=True, max_length=160, verbose_name='Invoice number')),
                ('number_of_attendees', models.PositiveIntegerField(default=5, verbose_name='Number of attendees')),
                ('auto_generated_on', models.DateTimeField(blank=True, null=True, verbose_name='Automatically generated on')),
                ('differing_billing_address', models.CharField(blank=True, max_length=256, verbose_name='Differing billing address')),
                ('import_id', models.CharField(blank=True, help_text='The ID of the record in the old system. This is used for referencing records even after migration.', max_length=256, verbose_name='Import ID')),
                ('activity_description', models.CharField(help_text='Please describe shortly what you are planning to do.', max_length=2048, verbose_name='Activity description')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['timespan'],
            },
        ),
        migrations.CreateModel(
            name='BookingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('text', models.CharField(max_length=800, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Booking Message',
                'verbose_name_plural': 'Booking Messages',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=160, verbose_name='Title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['get_human_readable_rule', 'title'])),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Unavailable')], verbose_name='Status')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('total_amount_per_occurrence', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total amount')),
                ('activity_description', models.CharField(help_text='Please describe shortly what you are planning to do.', max_length=2048, verbose_name='Activity description')),
                ('number_of_attendees', models.PositiveIntegerField(default=5, verbose_name='Number of attendees')),
                ('differing_billing_address', models.CharField(blank=True, max_length=256, verbose_name='Differing billing address')),
                ('import_id', models.CharField(blank=True, help_text='The ID of the record in the old system. This is used for referencing records even after migration.', max_length=256, verbose_name='Import ID')),
                ('rrule', models.TextField(verbose_name='Recurrence rule')),
                ('first_occurrence_date', models.DateField(verbose_name='First occurrence date')),
                ('last_occurrence_date', models.DateField(blank=True, null=True, verbose_name='Last occurrence date')),
                ('reminder_emails', models.BooleanField(default=True, verbose_name='Enable reminder e-mails')),
            ],
            options={
                'verbose_name': 'Recurrence rule',
                'verbose_name_plural': 'Recurrence rules',
                'ordering': ['created'],
            },
        ),
    ]
