# Generated by Django 5.1.1 on 2025-01-05 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('organizations', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='compensation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_of_compensation', related_query_name='booking_of_compensation', to='resources.compensation', verbose_name='Compensation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_of_organization', related_query_name='booking_of_organization', to='organizations.organization', verbose_name='Booking Organization'),
        ),
        migrations.AddField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_of_resource', related_query_name='booking_of_resource', to='resources.resource', verbose_name='Resource'),
        ),
    ]
