# Generated by Django 5.1.1 on 2025-01-20 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
        ('organizations', '0006_alter_emailtemplate_options'),
        ('resources', '0003_resource_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['resource'], name='bookings_bo_resourc_496d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['organization'], name='bookings_bo_organiz_a0d680_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_series'], name='bookings_bo_booking_d85d16_idx'),
        ),
    ]
