# Generated by Django 4.2.11 on 2024-07-07 15:23

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_end_time_booking_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['start_date', 'title']),
        ),
    ]
