# Generated by Django 5.1.1 on 2024-12-29 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_recurrencerule_bookingseries'),
        ('organizations', '0002_initial'),
        ('resources', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingseries',
            options={'ordering': ['created'], 'verbose_name': 'Booking series', 'verbose_name_plural': 'Booking series'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_of_bookingseries', related_query_name='booking_of_bookingseries', to='bookings.bookingseries', verbose_name='Recurrence rule'),
        ),
        migrations.AlterField(
            model_name='bookingseries',
            name='compensation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookingseries_set_of_compensation', related_query_name='bookingseries_of_compensation', to='resources.compensation', verbose_name='Compensation'),
        ),
        migrations.AlterField(
            model_name='bookingseries',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookingseries_set_of_organization', related_query_name='bookingseries_of_organization', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='bookingseries',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookingseries_set_of_resource', related_query_name='bookingseries_of_resource', to='resources.resource', verbose_name='Resource'),
        ),
        migrations.AlterField(
            model_name='bookingseries',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookingseries_set_of_user', related_query_name='bookingseries_of_user', to=settings.AUTH_USER_MODEL, verbose_name='Initial Booking User'),
        ),
    ]
