# Generated by Django 5.1.5 on 2025-02-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_bookings_bo_resourc_496d8d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingseries',
            name='total_amount_per_booking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total amount per booking'),
        ),
    ]
