# Generated by Django 4.2.11 on 2024-07-09 07:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('bookings', '0004_alter_booking_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rrule', models.CharField(max_length=200, verbose_name='Recurrence rule')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('first_occurrence_date', models.DateField(verbose_name='First occurrence date')),
                ('last_occurrence_date', models.DateField(verbose_name='Last occurrence date')),
                ('excepted_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(verbose_name='Excepted dates'), size=None)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrencerules_of_room', related_query_name='recurrencerule_of_room', to='resources.room', verbose_name='Resource')),
            ],
            options={
                'verbose_name': 'Recurrence rule',
                'verbose_name_plural': 'Recurrence rules',
                'ordering': ['created'],
            },
        ),
    ]
