# Generated by Django 5.1.1 on 2024-12-29 20:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bookingseries_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='recurrence_rule',
        ),
        migrations.RemoveField(
            model_name='bookingseries',
            name='first_occurrence_date',
        ),
        migrations.RemoveField(
            model_name='bookingseries',
            name='last_occurrence_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_of_bookingseries', related_query_name='booking_of_bookingseries', to='bookings.bookingseries', verbose_name='Booking series'),
        ),
        migrations.AddField(
            model_name='bookingseries',
            name='first_booking_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 29, 20, 56, 30, 194102, tzinfo=datetime.timezone.utc), verbose_name='Date of first booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingseries',
            name='last_booking_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of last booking'),
        ),
    ]
