# Generated by Django 4.2.11 on 2024-07-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_recurrencerule_excepted_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_of_recurrencerule', related_query_name='booking_of_recurrencerule', to='bookings.recurrencerule', verbose_name='Recurrence rule'),
        ),
    ]
