# Generated by Django 5.1.5 on 2025-02-15 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_end_date_alter_booking_end_time_and_more'),
        ('resources', '0007_alter_compensation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='compensation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_of_compensation', related_query_name='booking_of_compensation', to='resources.compensation', verbose_name='Compensation'),
            preserve_default=False,
        ),
    ]
