# Generated by Django 5.1.1 on 2025-01-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_recurrence_rule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingseries',
            old_name='total_amount_per_occurrence',
            new_name='total_amount_per_booking',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='differing_billing_address',
        ),
        migrations.RemoveField(
            model_name='bookingseries',
            name='differing_billing_address',
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Invoice address'),
        ),
        migrations.AddField(
            model_name='bookingseries',
            name='invoice_address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Invoice address'),
        ),
    ]
