# Generated by Django 4.2.11 on 2024-08-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_recurrence_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrencerule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='recurrencerule',
            name='room',
        ),
        migrations.RemoveField(
            model_name='recurrencerule',
            name='start_time',
        ),
    ]
