# Generated by Django 5.1.5 on 2025-02-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_compensation'),
        ('resources', '0007_alter_compensation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingseries',
            name='compensation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='bookingseries_set_of_compensation', related_query_name='bookingseries_of_compensation', to='resources.compensation', verbose_name='Compensation'),
            preserve_default=False,
        ),
    ]
