# Generated by Django 6.0 on 2026-01-24 11:11

import django.contrib.postgres.constraints
import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_bookingseries_compensation'),
        ('organizations', '0019_alter_emailtemplate_email_type'),
        ('resources', '0015_remove_resource_square_meters_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='uuid')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Unavailable')], verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Booking group',
                'verbose_name_plural': 'Booking groups',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='exclude_overlapping_reservations',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_item_booking',
            field=models.BooleanField(default=False, help_text='True for lendable item bookings. Used to exclude from overlap constraint.', verbose_name='Is item booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of items booked. Only applicable for lendable items.', verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookinggroups_of_organization', related_query_name='bookinggroup_of_organization', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookinggroups_of_user', related_query_name='bookinggroup_of_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_group',
            field=models.ForeignKey(blank=True, help_text='Groups lendable items booked together.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_of_bookinggroup', related_query_name='booking_of_bookinggroup', to='bookings.bookinggroup', verbose_name='Booking group'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_group'], name='bookings_bo_booking_087b2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 2), ('is_item_booking', False)), expressions=[('timespan', '&&'), ('resource', '=')], name='exclude_overlapping_reservations', violation_error_message='The requested timespan overlaps with an existing booking for this resource. Please chose another timespan.'),
        ),
    ]
