# Generated by Django 6.0.2 on 2026-02-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_bookinggroup_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP TABLE IF EXISTS django_q_ormq;
                DROP TABLE IF EXISTS django_q_schedule;
                DROP TABLE IF EXISTS django_q_task;
                """,
            reverse_sql="",
        ),
    ]
