# Generated by Django 6.0.2 on 2026-02-19 10:18

import random

from django.db import migrations, models
from django.utils import timezone


def generate_access_codes(apps, schema_editor):
    digits = "123456789"
    Booking = apps.get_model("bookings", "Booking")
    today = timezone.now().replace(hour=0, minute=0, second=0, microsecond=0)
    bookings = Booking.objects.filter(timespan__startswith__gte=today, access_code="")
    for booking in bookings:
        while True:
            code = "".join(random.choices(digits, k=6))
            if not code.startswith("12"):
                break
        booking.access_code = code
        booking.save(update_fields=["access_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_drop_django_q_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='access_code',
            field=models.CharField(blank=True, max_length=256, verbose_name='Code'),
        ),
        migrations.RunPython(generate_access_codes, migrations.RunPython.noop),
    ]
