# Generated by Django 6.0.2 on 2026-02-22 09:17

import re_sharing.bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='access_code',
            field=models.CharField(blank=True, default=re_sharing.bookings.models._generate_booking_access_code, max_length=256, verbose_name='Code'),
        ),
    ]
