# Generated by Django 5.1.1 on 2024-10-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_recurrencerule_last_occurrence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='auto_generated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Automatically generated on'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled')], default=1, verbose_name='Status'),
        ),
    ]
