# Generated by Django 6.0.2 on 2026-03-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_booking_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmessage',
            name='text',
            field=models.CharField(max_length=2048, verbose_name='Message'),
        ),
    ]
