# Generated by Django 6.0.3 on 2026-04-04 09:57

from django.db import migrations, models


def convert_empty_strings_to_json(apps, schema_editor):
    """Convert empty string values to '{}' before the column type change."""
    schema_editor.execute(
        "UPDATE bookings_booking SET invoice_address = '{}' WHERE invoice_address = ''"
    )
    schema_editor.execute(
        "UPDATE bookings_bookingseries SET invoice_address = '{}' WHERE invoice_address = ''"
    )
    # Wrap non-empty string values as JSON with the old_complete_invoice_address key
    schema_editor.execute(
        """UPDATE bookings_booking
           SET invoice_address = jsonb_build_object('old_complete_invoice_address', invoice_address)
           WHERE invoice_address != '{}'
             AND invoice_address IS NOT NULL"""
    )
    schema_editor.execute(
        """UPDATE bookings_bookingseries
           SET invoice_address = jsonb_build_object('old_complete_invoice_address', invoice_address)
           WHERE invoice_address != '{}'
             AND invoice_address IS NOT NULL"""
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_bookingmessage_text'),
    ]

    operations = [
        # Step 1: Convert string data to valid JSON while column is still text
        migrations.RunSQL(
            sql=[
                # Empty strings -> '{}'
                "UPDATE bookings_booking SET invoice_address = '{}' WHERE invoice_address = '';",
                "UPDATE bookings_bookingseries SET invoice_address = '{}' WHERE invoice_address = '';",
                # Non-empty strings -> {"old_complete_invoice_address": "<value>"}
                """UPDATE bookings_booking
                   SET invoice_address = json_build_object('old_complete_invoice_address', invoice_address)::text
                   WHERE invoice_address != '{}'
                     AND invoice_address IS NOT NULL;""",
                """UPDATE bookings_bookingseries
                   SET invoice_address = json_build_object('old_complete_invoice_address', invoice_address)::text
                   WHERE invoice_address != '{}'
                     AND invoice_address IS NOT NULL;""",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 2: Alter column type to JSONField
        migrations.AlterField(
            model_name='booking',
            name='invoice_address',
            field=models.JSONField(blank=True, default=dict, verbose_name='Invoice address'),
        ),
        migrations.AlterField(
            model_name='bookingseries',
            name='invoice_address',
            field=models.JSONField(blank=True, default=dict, verbose_name='Invoice address'),
        ),
    ]