# Generated by Django 5.1.1 on 2024-10-11 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_auto_generated_on_recurrencerule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='differing_billing_address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Differing billing address'),
        ),
        migrations.AlterField(
            model_name='bookingmessage',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingmessages_of_booking', related_query_name='bookingmessage_of_booking', to='bookings.booking', verbose_name='Booking'),
        ),
    ]
