# Generated by Django 5.1.1 on 2024-10-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_differing_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencerule',
            name='disable_reminder_emails',
            field=models.BooleanField(default=False, verbose_name='Disable reminder e-mails'),
        ),
    ]
