# Generated by Django 6.0.3 on 2026-10-02 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_invoice_address_to_jsonfield'),
        ('resources', '0020_compensation_counts_against_free_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='uses_free_booking',
            field=models.BooleanField(default=False, help_text="This booking used one of the organization's free bookings of the year.", verbose_name='Uses a free booking'),
        ),
        migrations.AddField(
            model_name='bookingseries',
            name='fallback_compensation',
            field=models.ForeignKey(blank=True, help_text="Paid compensation used for occurrences once the organization's free bookings of a year are used up.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookingseries_set_of_fallback_compensation', related_query_name='bookingseries_of_fallback_compensation', to='resources.compensation', verbose_name='Fallback compensation'),
        ),
        migrations.AddField(
            model_name='bookingseries',
            name='is_quota_priced',
            field=models.BooleanField(default=False, help_text="Occurrences of this series are priced individually against the organization's free bookings. Series created before the free bookings limit keep the series compensation.", verbose_name='Occurrences priced against free bookings'),
        ),
    ]
