# Generated by Django 5.1.1 on 2024-10-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_recurrencerule_disable_reminder_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrencerule',
            name='disable_reminder_emails',
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='reminder_emails',
            field=models.BooleanField(default=True, verbose_name='Enable reminder e-mails'),
        ),
    ]
