# Generated by Django 5.1.1 on 2024-11-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_booking_import_id_recurrencerule_import_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrencerule',
            name='excepted_dates',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Unavailable')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Unavailable')], default=1, verbose_name='Status'),
        ),
    ]
