# Generated by Django 5.1.1 on 2024-11-29 10:47

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_remove_recurrencerule_excepted_dates_and_more'),
        ('organizations', '0011_alter_defaultbookingstatus_status'),
        ('rooms', '0007_room_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencerule',
            name='compensation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rrules_of_compensation', related_query_name='rrule_of_compensation', to='rooms.compensation', verbose_name='Compensation'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='differing_billing_address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Differing billing address'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='end_time',
            field=models.TimeField(default='15:00:00', verbose_name='End Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='number_of_attendees',
            field=models.PositiveIntegerField(default=5, verbose_name='Number of attendees'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rrules_of_room', related_query_name='rrule_of_room', to='rooms.room', verbose_name='Room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['start_date', 'title']),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='start_date',
            field=models.DateField(default='2025-01-01', verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='start_time',
            field=models.TimeField(default='13:00:00', verbose_name='Start Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='title',
            field=models.CharField(default='migration-title', max_length=160, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rrules_of_user', related_query_name='rrule_of_user', to=settings.AUTH_USER_MODEL, verbose_name='Initial Booking User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rrules_of_organization', related_query_name='rrule_of_organization', to='organizations.organization', verbose_name='Recurrence Organization'),
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Unavailable')], verbose_name='Status'),
        ),
    ]
