# Generated by Django 5.1.1 on 2024-11-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_recurrencerule_compensation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrencerule',
            name='start_date',
        ),
    ]
