# Generated by Django 5.1.1 on 2024-11-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_alter_recurrencerule_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencerule',
            name='total_amount_per_occurrence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total amount'),
        ),
    ]
