# Generated by Django 5.1.1 on 2024-12-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_recurrencerule_total_amount_per_occurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=160, verbose_name='Invoice number'),
        ),
    ]
