# Generated by Django 5.1.1 on 2024-12-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_alter_recurrencerule_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='activity_description',
            field=models.CharField(default='', help_text='Please describe shortly what you are planning to do.', max_length=2048, verbose_name='Activity description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='activity_description',
            field=models.CharField(default='', help_text='Please describe shortly what you are planning to do.', max_length=2048, verbose_name='Activity description'),
            preserve_default=False,
        ),
    ]
