# Generated by Django 5.1.1 on 2024-12-26 22:25

import datetime
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_booking_activity_description_and_more'),
        ('organizations', '0021_emailtemplate_active_alter_emailtemplate_email_type'),
        ('resources', '0009_alter_roomimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 12, 26), verbose_name='End Date'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='booking',
            index=django.contrib.postgres.indexes.GistIndex(fields=['timespan'], name='bookings_bo_timespa_b881a5_gist'),
        ),
    ]
