# Generated by Django 4.2.11 on 2024-04-04 14:47

import django.contrib.postgres.constraints
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='exclude_overlapping_reservations',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('timespan', '&&'), ('room', '=')], name='exclude_overlapping_reservations', violation_error_message='The requested timespan overlaps with an existing booking for this room. Please chose another timespan.'),
        ),
    ]
