# Generated by Django 4.2.11 on 2024-04-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('bookings', '0002_remove_booking_exclude_overlapping_reservations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinggroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookinggroups_of_organization', related_query_name='bookinggroup_of_organization', to='organizations.organization', verbose_name='Booking Organization'),
        ),
    ]
