# Generated by Django 4.2.11 on 2024-05-08 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('rooms', '0002_alter_room_pricing'),
        ('bookings', '0002_remove_booking_exclude_overlapping_reservations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_group',
        ),
        migrations.AddField(
            model_name='booking',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_of_organization', related_query_name='booking_of_organization', to='organizations.organization', verbose_name='Booking Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(default='Test', max_length=160, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_of_user', related_query_name='booking_of_user', to=settings.AUTH_USER_MODEL, verbose_name='Initial Booking User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinggroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookinggroups_of_organization', related_query_name='bookinggroup_of_organization', to='organizations.organization', verbose_name='Booking Organization'),
        ),
        migrations.CreateModel(
            name='RecurrencePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence', recurrence.fields.RecurrenceField()),
                ('start_datetime', models.DateTimeField(verbose_name='Start datetime')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration in minutes')),
                ('recurrence_end', models.DateTimeField(null=True, verbose_name='End datetime')),
                ('title', models.CharField(max_length=160, verbose_name='Title')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrencepatterns_of_organization', related_query_name='recurrencepattern_of_organization', to='organizations.organization', verbose_name='Booking Organization')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrencepatterns_of_room', related_query_name='recurrencepattern_of_room', to='rooms.room', verbose_name='Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrencepatterns_of_user', related_query_name='recurrencepattern_of_user', to=settings.AUTH_USER_MODEL, verbose_name='Initial Booking User')),
            ],
            options={
                'verbose_name': 'Recurrence Pattern',
                'verbose_name_plural': 'Recurrence Patterns',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_of_recurrencepattern', related_query_name='booking_of_recurrencepattern', to='bookings.recurrencepattern', verbose_name='Recurrence Pattern'),
        ),
    ]
