# Generated by Django 4.2.11 on 2024-05-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_booking_group_booking_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrencepattern',
            name='recurrence_end',
            field=models.DateField(null=True, verbose_name='End date'),
        ),
    ]
