# Generated by Django 4.2.11 on 2024-04-29 11:36

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_pricing'),
        ('bookings', '0003_alter_bookinggroup_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrencePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence', recurrence.fields.RecurrenceField()),
                ('start_datetime', models.DateTimeField(verbose_name='Start datetime')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration in minutes')),
                ('recurrence_end', models.DateTimeField(verbose_name='End datetime')),
                ('booking_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrencepatterns_of_bookinggroup', related_query_name='recurrencepattern_of_bookinggroup', to='bookings.bookinggroup', verbose_name='Booking Group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrencepatterns_of_room', related_query_name='recurrencepattern_of_room', to='rooms.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Recurrence Pattern',
                'verbose_name_plural': 'Recurrence Patterns',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_of_recurrencepattern', related_query_name='booking_of_recurrencepattern', to='bookings.recurrencepattern', verbose_name='Recurrence Pattern'),
        ),
    ]
