# Generated by Django 4.2.11 on 2024-05-14 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_alter_bookinggroup_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_group',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='uuid',
        ),
        migrations.AddField(
            model_name='booking',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_of_organization', related_query_name='booking_of_organization', to='organizations.organization', verbose_name='Booking Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(default='title', max_length=160, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_of_user', related_query_name='booking_of_user', to=settings.AUTH_USER_MODEL, verbose_name='Initial Booking User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookingGroup',
        ),
    ]
