# Generated by Django 4.2.11 on 2024-05-14 08:52

import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_booking_group_remove_booking_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='exclude_overlapping_reservations',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled')], default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 2)), expressions=[('timespan', '&&'), ('room', '=')], name='exclude_overlapping_reservations', violation_error_message='The requested timespan overlaps with an existing booking for this room. Please chose another timespan.'),
        ),
    ]
