# Generated by Django 4.2.11 on 2024-05-21 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0005_remove_booking_exclude_overlapping_reservations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('text', models.CharField(max_length=800, verbose_name='Message text')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookingmessages_of_booking', related_query_name='bookingmessage_of_booking', to='bookings.booking', verbose_name='Booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookingmessages_of_user', related_query_name='bookingmessage_of_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
