# Generated by Django 4.2.11 on 2024-07-09 07:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_recurrencerule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrencerule',
            name='excepted_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, size=None, verbose_name='Excepted dates'),
        ),
    ]
