# Generated by Django 5.1.1 on 2024-09-12 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_recurrencerule_end_time_and_more'),
        ('rooms', '0003_compensation'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='compensation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_of_compensation', related_query_name='booking_of_compensation', to='rooms.compensation', verbose_name='Compensation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Amount'),
        ),
    ]
