# Generated by Django 4.2.11 on 2024-05-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingmessage',
            options={'ordering': ['created'], 'verbose_name': 'Booking Message', 'verbose_name_plural': 'Booking Messages'},
        ),
        migrations.AlterField(
            model_name='bookingmessage',
            name='text',
            field=models.CharField(max_length=800, verbose_name='Message'),
        ),
    ]
