# Generated by Django 5.1.1 on 2024-09-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_attendees',
            field=models.PositiveIntegerField(default=5, verbose_name='Number of attendees'),
        ),
    ]
