# Generated by Django 5.1.1 on 2024-10-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_number_of_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrencerule',
            name='last_occurrence_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last occurrence date'),
        ),
    ]
