# Generated by Django 5.1.1 on 2024-11-18 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_remove_recurrencerule_disable_reminder_emails_and_more'),
        ('organizations', '0010_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='import_id',
            field=models.CharField(blank=True, help_text='The ID of the record in the old system. This is used for referencing records even after migration.', max_length=256, verbose_name='Import ID'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='import_id',
            field=models.CharField(blank=True, help_text='The ID of the record in the old system. This is used for referencing records even after migration.', max_length=256, verbose_name='Import ID'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='rrule',
            field=models.TextField(verbose_name='Recurrence rule'),
        ),
    ]
