# Generated by Django 5.1.1 on 2024-11-29 11:01

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_remove_recurrencerule_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrencerule',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['get_human_readable_rule', 'title']),
        ),
    ]
