# Generated by Django 5.1.1 on 2024-12-19 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_booking_invoice_number'),
        ('organizations', '0021_emailtemplate_active_alter_emailtemplate_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrencerule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rrules_of_organization', related_query_name='rrule_of_organization', to='organizations.organization', verbose_name='Organization'),
        ),
    ]
